name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          config_timezone: Europe/Riga
          template: classic
          base: header, activity, metadata
          repositories_skipped: 0wlie22/0wlie22
          output_action: commit
          committer_message: "Update metrics"
          
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, txt, css
